# Generated by Django 4.2.4 on 2023-11-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevistado',
            name='trabajador_dependiente',
            field=models.BooleanField(default=False),
        ),
    ]
